apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-pods-config-j12t
  namespace: j12t
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = true
      logtarget = "file"
      logfile = "/tmp/telegraf.log"
    [[outputs.prometheus_client]]
      listen = ":9126"
      path = "/metrics"
    [[outputs.file]]
      files = ["/tmp/telegraf_stats.txt"]
      data_format = "wavefront"
      rotation_max_size = "5MB"
    [[inputs.mem]]
    [[inputs.cpu]]
    [[inputs.net]]
    [[inputs.diskio]]
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-server
  labels:
    app: simpleapp-server
  namespace: j12t
spec:
  ports:
  - port: 8888
    name: simpleapp
  - port: 9126
    name: telegraf
  clusterIP: None
  selector:
    app: simpleapp-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleapp
  namespace: j12t
spec:
  selector:
    matchLabels:
      app: simpleapp-server # has to match .spec.template.metadata.labels
  serviceName: simpleapp-server # has to match headless Service metadata.name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: simpleapp-server # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: simpleapp-server
        image: jerapiblannett/loadbalancer-app-709c7:plain
        ports:
        - containerPort: 8888
        resources:
          requests:
            ephemeral-storage: "1G"
          limits:
            ephemeral-storage: "1G"
        volumeMounts:
        - name: ephemeral
          mountPath: "/tmp"
        imagePullPolicy: Always
      - name: telegraf-agent
        image: telegraf:1.20
        ports:
        - containerPort: 9126
        resources:
          requests:
            ephemeral-storage: "50M"
          limits:
            ephemeral-storage: "100M"
        volumeMounts:
        - name: ephemeral
          mountPath: "/tmp"
        - name: telegraf-pods-config-j12t
          mountPath: "/etc/telegraf"
      volumes:
      - name: ephemeral
        emptyDir:
          sizeLimit: "2G"
      - name: telegraf-pods-config-j12t
        configMap:
          name: telegraf-pods-config-j12t
          defaultMode: 420

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simpleapp-nginx-config-j12t
  namespace: j12t
data:
  j12t.conf: |
    upstream backend {
      least_conn;
      server simpleapp-0.simpleapp-server.j12t.svc.cluster.local:8888;
      server simpleapp-1.simpleapp-server.j12t.svc.cluster.local:8888;
      # server simpleapp-2.simpleapp-server.j12t.svc.cluster.local:8888;
    }
    server {
      listen 80;
      location / {
          # proxy_set_header X-Real-IP $remote_addr;
          # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          # proxy_set_header Host $http_host;
          #tell Nginx to distribute the load
          proxy_pass http://backend/;
          # proxy_http_version 1.1;
          # proxy_set_header Upgrade $http_upgrade;
          # proxy_set_header Connection "upgrade";
          proxy_read_timeout 1800;
          proxy_connect_timeout 1800;
          proxy_send_timeout 1800;
          send_timeout 1800;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-nginx
  namespace: j12t
  labels:
    app: simpleapp-nginx
spec:
  type: NodePort
  selector:
    app: simpleapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx
    - port: 9126
      name: telegraf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleapp-nginx
  namespace: j12t
spec:
  selector:
    matchLabels:
      app: simpleapp-nginx # has to match .spec.template.metadata.labels
  serviceName: simpleapp-nginx # has to match headless Service metadata.name
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: simpleapp-nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: simpleapp-nginx-config-j12t
          configMap:
            name: simpleapp-nginx-config-j12t
            defaultMode: 420
        - name: ephemeral
          emptyDir:
            sizeLimit: "100M"
        - name: telegraf-pods-config-j12t
          configMap:
            name: telegraf-pods-config-j12t
            defaultMode: 420
      containers:
      - name: simpleapp-nginx
        image: nginx:latest
        volumeMounts:
          - name: simpleapp-nginx-config-j12t
            mountPath: /etc/nginx/conf.d
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: telegraf-agent
        image: telegraf:1.20
        ports:
        - containerPort: 9126
        resources:
          requests:
            ephemeral-storage: "50M"
          limits:
            ephemeral-storage: "100M"
        volumeMounts:
        - name: ephemeral
          mountPath: "/tmp"
        - name: telegraf-pods-config-j12t
          mountPath: "/etc/telegraf"